Repository ClimateImpactLab/downscaleCMIP6, pull requests merged in 2021-11, with the labels that each got.

#290 Test new xclim in dodola:dev for biascorrectdownscale step
  workflows/templates/biascorrectdownscale.yaml
Labels: enhancement

#291 Pin all dodola:dev image refs to new dodola:0.7.0 release
  workflows/templates/biascorrectdownscale.yaml
  workflows/templates/distributed-regrid.yaml
  workflows/templates/qualitycontrol-check-cmip6.yaml
  workflows/templates/regrid.yaml
Labels: enhancement

#293 Add lightweight units metadata to era5 in cleaning
  workflows/templates/clean-era5.yaml
Labels: bug

#294 Fix apply-aiqpd OOM, bad coordinate error with dodola v0.7.0
  workflows/templates/biascorrectdownscale.yaml
Labels: bug

#296 Switch QC template back to dodola command
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: enhancement

#295 Add workflow template for QDM logic
  workflows/templates/kustomization.yaml
  workflows/templates/qdm.yaml
Labels: enhancement

#298 Fix OOMKilled error in QC with dodola validate-dataset
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug

#299 Add workflow template for AIQPD logic
  workflows/templates/aiqpd.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#300 Fix potentially non-unique argo scratch paths
  infrastructure/kubernetes-az/argo/patches/workflow-controller-configmap.yaml
  infrastructure/kubernetes-gcp/argo/patches/workflow-controller-configmap.yaml
  workflows/templates/aiqpd.yaml
  workflows/templates/clean-cmip6.yaml
  workflows/templates/distributed-regrid.yaml
  workflows/templates/qdm.yaml
  workflows/templates/rechunk.yaml
  workflows/templates/regrid.yaml
Labels: bug

#301 Simplify template use external qdm, aiqpd
  workflows/templates/biascorrectdownscale.yaml
Labels: enhancement

#303 Swap train-aiqpd script for dodola train-aiqpd
  workflows/templates/aiqpd.yaml
Labels: enhancement

#304 Swap QDM workflow scripts for dodola commands
  workflows/templates/qdm.yaml
Labels: enhancement

#306 Swap AIQPD workflow scripts for dodola commands
  workflows/templates/aiqpd.yaml
Labels: bug, enhancement

#307 updates to global validation with dask
  notebooks/downscaling_pipeline/global_validation_manual.ipynb
  notebooks/downscaling_pipeline/science_validation_manual.py
Labels: enhancement

#309 Upgrade all workflow dodola images to v0.8.0 release
  workflows/templates/catalog.yaml
  workflows/templates/clean-cmip6.yaml
  workflows/templates/clean-era5.yaml
  workflows/templates/distributed-regrid.yaml
  workflows/templates/download-cmip6.yaml
  workflows/templates/qdm.yaml
  workflows/templates/qplad.yaml
  workflows/templates/qualitycontrol-check-cmip6.yaml
  workflows/templates/rechunk.yaml
  workflows/templates/regrid.yaml
  workflows/templates/zarr-transfer.yaml
Labels: enhancement

#311 Organize era5 notebooks
  notebooks/era5_validation/check_antarctica_temperature_data.ipynb
  notebooks/era5_validation/era5_climatology_files_created.ipynb
  notebooks/era5_validation/explore_era5_grids.ipynb
  notebooks/era5_validation/test_precip_closed_sum.ipynb
  notebooks/global_validation/global_validation_dtr_v2.ipynb
  notebooks/global_validation/global_validation_tasmax_v2.ipynb
  notebooks/global_validation/science_validation.ipynb
  notebooks/qplad_validation/check_aiqpd_downscaled_data.ipynb
  notebooks/qplad_validation/prototype_analog_method_scaling.ipynb
  notebooks/qplad_validation/synthetic_test_spatial_disaggregation.ipynb
Labels: enhancement

#319 Add WorkflowTemplate for output metadata maker
  workflows/templates/create-output-metadata-json.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#320 Switch workflow QDM and QPLAD to set output metadata with JSON
  workflows/templates/qdm.yaml
  workflows/templates/qplad.yaml
Labels: enhancement

#321 Fix bad `dc6_grid` values in downscaled output
  workflows/templates/create-output-metadata-json.yaml
Labels: bug

#322 Pin QDM, QPLAD templates to dodola:0.9.0 for metadata improvements
  workflows/templates/qdm.yaml
  workflows/templates/qplad.yaml
Labels: enhancement

#324 Promote e2e-tasmax into e2e-tasmax-jobs template, refactor parameters
  workflows/templates/biascorrectdownscale.yaml
  workflows/templates/e2e-tasmax-jobs.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#325 Minor fix to downscaling metadata from feedback
  workflows/templates/create-output-metadata-json.yaml
Labels: bug

#329 Fix bad overwrite param passing from "e2e-tasmax"
  workflows/templates/download-cmip6.yaml
Labels: bug

#330 Bump argo workflows to v3.2.4 release
  infrastructure/kubernetes-gcp/argo/kustomization.yaml
Labels: enhancement

#332 Add e2e pr workflowtemplate
  workflows/templates/e2e-pr-jobs.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#333 Add WorkflowTemplate to compute dtr
  workflows/templates/compute-dtr.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#334 Various fixes and improvements to compute_dtr WorkflowTemplate
  workflows/templates/compute-dtr.yaml
Labels: bug

#335 Add end-to-end diurnal temperature range (dtr) workflowtemplate
  workflows/templates/biascorrectdownscale.yaml
  workflows/templates/clean-cmip6.yaml
  workflows/templates/download-cmip6.yaml
  workflows/templates/e2e-dtr-jobs.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#337 Move cmip6-in-the-cloud download catalog to "noQC"
  workflows/templates/download-cmip6.yaml
Labels: bug, enhancement

#336 fix parameter files
  workflows/parameters/ACCESS-ESM1-5-pr.yaml
  workflows/parameters/ACCESS-ESM1-5-tasmin.yaml
Labels: bug

#338 Fix reference to non-existant GFDL ssp370 for historical precip run
  workflows/parameters/GFDL-CM4-pr.yaml
Labels: bug

#339 Allow 0 < dtr < 70 through QC, bump QDM, QPLAD dodola to v0.10.0 release
  workflows/templates/qdm.yaml
  workflows/templates/qplad.yaml
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: enhancement, dependencies

#343 fix version number for ssp585
  workflows/parameters/ACCESS-ESM1-5-tasmax.yaml
Labels: bug

#350 Fix bad parameter file formatting
  workflows/parameters/MPI-ESM1-2-HAM-tasmax.yaml
Labels: bug

#363 swap 0.10.0 for dev
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug

#351 Crop ssp dataset on from 2015 to 2110 on entrance to cleaning step
  workflows/templates/clean-cmip6.yaml
Labels: enhancement
