Repository ClimateImpactLab/downscaleCMIP6, pull requests merged in 2021-09, with the labels that each got.

#161 Add prototype AIQPD downscale workflow
  workflows/templates/dc6.yaml
  workflows/templates/downscale.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#164 Workaround x509 cert signed by unknown authority from argo-server
  infrastructure/kubernetes/argo/kustomization.yaml
Labels: bug

#165 Add workflow template to transfer Zarr Stores between cloud storage
  workflows/templates/kustomization.yaml
  workflows/templates/zarr-transfer.yaml
Labels: enhancement

#166 Remove cruft event sensors and triggers
  infrastructure/kubernetes/workflows-default/events/clean-cmip6-dtr-sensor.yaml
  infrastructure/kubernetes/workflows-default/events/clean-cmip6-pr-sensor.yaml
  infrastructure/kubernetes/workflows-default/events/clean-cmip6-tas-sensor.yaml
  infrastructure/kubernetes/workflows-default/events/download-cmip6-sensor.yaml
  infrastructure/kubernetes/workflows-default/events/kustomization.yaml
Labels: bug

#170 Migrate rough downscale workflow scripts to dodola:0.6.0 functions
  workflows/templates/downscale.yaml
Labels: enhancement

#168 add aiqpd method dev and testing notebooks
  notebooks/check_aiqpd_downscaled_data.ipynb
  notebooks/downscaling_pipeline/aiqpd_method_testing.ipynb
  notebooks/prototype_analog_method_scaling.ipynb
  notebooks/synthetic_test_spatial_disaggregation.ipynb
Labels: enhancement

#172 Add back fleshed-out storage containers
  infrastructure/terraform/modules/storage_account/main.tf
Labels: enhancement

#173 Minor memory bump, cleanup based on new GCMs
  workflows/templates/download-cmip6.yaml
Labels: enhancement

#160 Migrate clean, download workflows to new Azure storage containers
  workflows/templates/clean-cmip6.yaml
  workflows/templates/clean-era5.yaml
  workflows/templates/download-cmip6.yaml
Labels: enhancement

#174 Removes old, unused workflows, catalog, json target list
  workflows/clean-cmip6-workflow.yaml
  workflows/clean-era5-workflow.yaml
  workflows/cmip6run-targets.json
  workflows/dc6-workflow.yaml
  workflows/download-cmip6-workflow.yaml
  workflows/intake-catalog.yaml
Labels: enhancement

#171 add parameter files for tasmax model runs
  workflows/parameters/AWI-CM-1-1-MR-tasmax.yaml
  workflows/parameters/BCC-CSM2-MR-tasmax.yaml
  workflows/parameters/CNRM-CM6-1-tasmax.yaml
  workflows/parameters/CanESM5-tasmax.yaml
  workflows/parameters/EC-Earth3-tasmax.yaml
  workflows/parameters/FGOALS-g3-tasmax.yaml
  workflows/parameters/INM-CM5-0-tasmax.yaml
  workflows/parameters/KACE-1-0-G-tasmax.yaml
  workflows/parameters/MIROC6-tasmax.yaml
  workflows/parameters/NorESM2-LM-tasmax.yaml
Labels: enhancement

#186 Refactor "dc6" template to "biascorrect" for clarity
  workflows/templates/biascorrect.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#217 Fix bug where cleaned SSPs have historical attrs
  workflows/templates/clean-cmip6.yaml
Labels: bug

#218 Add workflow template for standardized fsspec URLs
  workflows/templates/catalog.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#219 Add proper biascorrect output using Zarr metadata, bug fixes
  workflows/templates/biascorrect.yaml
Labels: enhancement

#221 Downscale on multiple SSPs, output downscaled to proper storage bucket
  workflows/templates/downscale.yaml
Labels: enhancement

#222 Update parameter design to allow multiple independent SSP, historical runs
  workflows/parameters/ACCESS-ESM1-5-pr.yaml
  workflows/parameters/ACCESS-ESM1-5-tasmax.yaml
  workflows/parameters/ACCESS-ESM1-5-tasmin.yaml
  workflows/parameters/AWI-CM-1-1-MR-tasmax.yaml
  workflows/parameters/BCC-CSM2-MR-tasmax.yaml
  workflows/parameters/CNRM-CM6-1-tasmax.yaml
  workflows/parameters/CanESM5-tasmax.yaml
  workflows/parameters/EC-Earth3-tasmax.yaml
  workflows/parameters/FGOALS-g3-tasmax.yaml
  workflows/parameters/GFDL-ESM4-pr.yaml
  workflows/parameters/GFDL-ESM4-tasmax.yaml
  workflows/parameters/GFDL-ESM4-tasmin.yaml
  workflows/parameters/INM-CM5-0-tasmax.yaml
  workflows/parameters/KACE-1-0-G-tasmax.yaml
  workflows/parameters/MIROC6-tasmax.yaml
  workflows/parameters/NorESM2-LM-tasmax.yaml
  workflows/templates/biascorrect.yaml
  workflows/templates/biascorrectdownscale.yaml
  workflows/templates/clean-cmip6.yaml
  workflows/templates/download-cmip6.yaml
  workflows/templates/downscale.yaml
  workflows/templates/kustomization.yaml
Labels: bug, enhancement

#239 Fix OOM error on EC-Earth3 in standardize step of "clean-cmip6"
  workflows/templates/clean-cmip6.yaml
Labels: bug

#240 Add cyclic pixel to fix dateline artifact in downscale output
  workflows/templates/biascorrectdownscale.yaml
Labels: bug

#272 Fix cmip6 clean chunking bug
  workflows/parameters/CNRM-CM6-1-tasmin.yaml
  workflows/templates/clean-cmip6.yaml
Labels: bug

#271 Improve cleaning memory for EC-Earth3 family simulations
  workflows/templates/clean-cmip6.yaml
Labels: bug

#257 add tasmin and pr yamls
  workflows/parameters/CNRM-CM6-1-pr.yaml
  workflows/parameters/CNRM-CM6-1-tasmin.yaml
  workflows/parameters/CNRM-ESM2-1-tasmin.yaml
  workflows/parameters/CanESM5-pr.yaml
  workflows/parameters/CanESM5-tasmin.yaml
  workflows/parameters/EC-Earth3-Veg-LR-pr.yaml
  workflows/parameters/EC-Earth3-Veg-LR-tasmin.yaml
  workflows/parameters/EC-Earth3-Veg-pr.yaml
  workflows/parameters/EC-Earth3-Veg-tasmin.yaml
  workflows/parameters/EC-Earth3-pr.yaml
  workflows/parameters/EC-Earth3-tasmin.yaml
  workflows/parameters/MRI-ESM2-0-pr.yaml
  workflows/parameters/MRI-ESM2-0-tasmin.yaml
Labels: tasmin CMIP6 data downloading/cleaning

#273 fix merge conflict that got overlooked
  workflows/parameters/CNRM-CM6-1-tasmin.yaml
Labels: bug
