Repository ClimateImpactLab/downscaleCMIP6, pull requests merged in 2021-12, with the labels that each got.

#364 qdm output lastyear dynamic set to 2099 or 2100
  workflows/templates/qdm.yaml
Labels: bug

#365 Increase tasmax, timesteps allowed by QC checks
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug, enhancement

#377 Drop NAN-filled runs from parameter files
  workflows/parameters/ACCESS-CM2-tasmax.yaml
  workflows/parameters/ACCESS-ESM1-5-tasmax.yaml
  workflows/parameters/MRI-ESM2-0-tasmax.yaml
Labels: bug

#382 Fix QDM bias correction of historical getting bad last-year parameter
  workflows/templates/biascorrectdownscale.yaml
  workflows/templates/qdm.yaml
Labels: bug

#384 fix version number
  workflows/parameters/NorESM2-MM-tasmax.yaml
Labels: bug

#425 Fixes various format errors and references to non-existing data
  workflows/parameters/ACCESS-ESM1-5-pr.yaml
  workflows/parameters/ACCESS-ESM1-5-tasmin.yaml
  workflows/parameters/GFDL-CM4-tasmax.yaml
  workflows/parameters/GFDL-CM4-tasmin.yaml
  workflows/parameters/GFDL-ESM4-tasmin.yaml
  workflows/parameters/MPI-ESM-1-2-HAM-pr.yaml
  workflows/parameters/MPI-ESM-1-2-HAM-tasmin.yaml
  workflows/parameters/NorESM2-MM-pr.yaml
  workflows/parameters/NorESM2-MM-tasmin.yaml
Labels: bug, parameter file

#428 Add DTR parameter files based on tasmin, tasmax
  workflows/parameters/ACCESS-ESM1-5-dtr.yaml
  workflows/parameters/CanESM5-dtr.yaml
  workflows/parameters/EC-Earth3-Veg-LR-dtr.yaml
  workflows/parameters/EC-Earth3-Veg-dtr.yaml
  workflows/parameters/EC-Earth3-dtr.yaml
  workflows/parameters/GFDL-CM4-dtr.yaml
  workflows/parameters/GFDL-ESM4-dtr.yaml
  workflows/parameters/INM-CM4-8-dtr.yaml
  workflows/parameters/INM-CM5-0-dtr.yaml
  workflows/parameters/KIOST-ESM-dtr.yaml
  workflows/parameters/MIROC-ES2L-dtr.yaml
  workflows/parameters/MIROC6-dtr.yaml
  workflows/parameters/MPI-ESM-1-2-HAM-dtr.yaml
  workflows/parameters/MPI-ESM1-2-HR-dtr.yaml
  workflows/parameters/MPI-ESM1-2-LR-dtr.yaml
  workflows/parameters/MRI-ESM2-0-dtr.yaml
  workflows/parameters/NESM3-dtr.yaml
  workflows/parameters/NorESM2-LM-dtr.yaml
  workflows/parameters/NorESM2-MM-dtr.yaml
Labels: enhancement, parameter file

#429 Fix biascorrection failing run ending in 2099
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug

#432 remove MPI-ESM-1-2-HAM model because tasmax output only goes to 2055
  workflows/parameters/MPI-ESM-1-2-HAM-dtr.yaml
  workflows/parameters/MPI-ESM-1-2-HAM-pr.yaml
  workflows/parameters/MPI-ESM-1-2-HAM-tasmax.yaml
  workflows/parameters/MPI-ESM-1-2-HAM-tasmin.yaml
Labels: bug

#434 explore and modify cmip6 dtr if negative values are present
  notebooks/downscaling_pipeline/cmip6_dtr.ipynb
Labels: bug

#433 Add apply-dtr-minimum-threshold parameter
  workflows/templates/biascorrectdownscale.yaml
  workflows/templates/e2e-dtr-jobs.yaml
  workflows/templates/e2e-pr-jobs.yaml
  workflows/templates/e2e-tasmax-jobs.yaml
  workflows/templates/qdm.yaml
Labels: enhancement

#444 Add stable, QDM-preprocessing as workflowTemplate
  workflows/templates/kustomization.yaml
  workflows/templates/qdm-preprocess.yaml
Labels: bug, enhancement

#446 Add automated backups to dev argo sql instance
  infrastructure/terraform/gcp-core/modules/datalake_storage/main.tf
Labels: enhancement, infrastructure

#445 Fix sporadic timeouts in QDM preprocessing
  workflows/templates/qdm.yaml
Labels: bug

#448 Bump argo workflows to v3.2.5
  infrastructure/kubernetes-gcp/argo/kustomization.yaml
Labels: infrastructure

#454 Fix failing precipitation regridding in QDM bias-correction
  workflows/templates/qdm-preprocess.yaml
Labels: bug

#455 Fix failing precipitation regrid in QPLAD downscaling steps
  workflows/templates/qplad.yaml
Labels: bug

#456 Dirty fix to ERA-5 precipitation data being "tp"
  workflows/templates/clean-era5.yaml
Labels: bug

#457 Add GKE metrics scraper for argo wrk controller
  infrastructure/kubernetes-gcp/argo/kustomization.yaml
  infrastructure/kubernetes-gcp/argo/workflow-controller-monitor.yaml
Labels: enhancement

#459 Fix dtr polar validation in dodola dev release
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug

#460 Drop erroring GKE workflow metrics PodMonitor
  infrastructure/kubernetes-gcp/argo/kustomization.yaml
  infrastructure/kubernetes-gcp/argo/workflow-controller-monitor.yaml
Labels: bug, infrastructure

#461 Allow 0s in clean CMIP6 DTR validation check
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug

#462 Test fix for bad precip wetday correction and precip max validation
  workflows/templates/qdm-preprocess.yaml
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug

#465 update reanalysis preprocessing to use wet day frequency correction i…
  workflows/templates/qdm.yaml
Labels: bug

#478 Test wet-day frequency tweak in dodola:dev
  workflows/templates/qdm-preprocess.yaml
Labels: bug

#471 Add remaining tasmin pr parameter files
  workflows/parameters/ACCESS-CM2-pr.yaml
  workflows/parameters/ACCESS-CM2-tasmin.yaml
  workflows/parameters/AWI-CM-1-1-MR-tasmin.yaml
  workflows/parameters/FGOALS-g3-pr.yaml
  workflows/parameters/FGOALS-g3-tasmin.yaml
Labels: pr bias correction and downscaling run, dtr bias correction and downscaling run

#479 add tasmin and pr parameter files for BCC-CSM2-MR model
  workflows/parameters/BCC-CSM2-MR-pr.yaml
  workflows/parameters/BCC-CSM2-MR-tasmin.yaml
Labels: pr bias correction and downscaling run, dtr bias correction and downscaling run

#480 Add new DTR parameter files
  workflows/parameters/ACCESS-CM2-dtr.yaml
  workflows/parameters/AWI-CM-1-1-MR-dtr.yaml
  workflows/parameters/BCC-CSM2-MR-dtr.yaml
  workflows/parameters/FGOALS-g3-dtr.yaml
Labels: enhancement, parameter file

#485 Add biascorrectdownscale-precipitation workflowTemplate with ceiling
  workflows/templates/biascorrectdownscale-precipitation.yaml
  workflows/templates/e2e-pr-jobs.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement

#352 add post-downscaling wet day correction in the workflows
  workflows/templates/biascorrectdownscale.yaml
  workflows/templates/qplad.yaml
Labels: enhancement

#486 Fix param passing between qplad and biascorrecdownscale-precipitation
  workflows/templates/biascorrectdownscale-precipitation.yaml
Labels: bug

#489 Fixes typo in dodola command option
  workflows/templates/qplad.yaml
Labels: bug

#490 Add wet-day frequency correction to QPLAD fine, coarse reference creation
  workflows/templates/biascorrectdownscale-precipitation.yaml
  workflows/templates/qplad.yaml
Labels: bug

#491 Fix inconsistency bug: move wet-day correct to before regridding
  workflows/templates/qplad.yaml
Labels: bug

#492 Fix no --wetday-post-correction error
  workflows/templates/qplad.yaml
Labels: bug

#495 reposition DTR floor application in biascorrectdownscale-DTR
  workflows/templates/biascorrectdownscale-dtr.yaml
  workflows/templates/e2e-dtr-jobs.yaml
Labels: bug

#498 Highmem core nodes for more parallel runs
  infrastructure/terraform/gcp-core/modules/gke_argo_cluster/main.tf
Labels: enhancement, infrastructure

#496 Bump argo to patch bad emissary default mounting
  infrastructure/kubernetes-gcp/argo/kustomization.yaml
Labels: bug

#499 Scale-down core nodes to standard memory
  infrastructure/terraform/gcp-core/modules/gke_argo_cluster/main.tf
Labels: infrastructure
