Repository ClimateImpactLab/downscaleCMIP6, pull requests merged in 2021-06, with the labels that each got.

#94 Relocate existing k8s/terraform infrastructure
  .gitignore
  infrastructure/kubernetes/README.md
  infrastructure/kubernetes/argo/kustomization.yaml
  infrastructure/kubernetes/argo/patches/add-default-artifact-repository.yaml
  infrastructure/kubernetes/argo/patches/change-aks-containerruntimeexecutor.yaml
  infrastructure/kubernetes/minio/.helmignore
  infrastructure/kubernetes/minio/Chart.yaml
  infrastructure/kubernetes/minio/values.yaml
  infrastructure/kubernetes/workflows-default/kustomization.yaml
  infrastructure/kubernetes/workflows-default/workflow-role.yaml
  infrastructure/kubernetes/workflows-default/workflows-default-rolebinding.yaml
  infrastructure/kubernetes/workflows-default/workflows-default-serviceaccount.yaml
  infrastructure/terraform/.terraform.lock.hcl
  infrastructure/terraform/HISTORY.md
  infrastructure/terraform/README.md
  infrastructure/terraform/main.tf
  infrastructure/terraform/modules/aks_cluster/main.tf
  infrastructure/terraform/modules/aks_cluster/outputs.tf
  infrastructure/terraform/modules/aks_cluster/variables.tf
  infrastructure/terraform/modules/kubernetes_internal/main.tf
  infrastructure/terraform/modules/kubernetes_internal/variables.tf
  infrastructure/terraform/modules/storage_account/main.tf
  infrastructure/terraform/modules/storage_account/outputs.tf
  infrastructure/terraform/modules/storage_account/variables.tf
  infrastructure/terraform/variables.tf
Labels: enhancement

#100 update validation for easier debugging
  notebooks/era5_workflow/validate_era5_hourlyORdaily_files.ipynb
Labels: enhancement

#106 update time slicing for ref and hist
  workflows/clean-cmip6-workflow.yaml
Labels: bug

#107 Give argo workers heavy dask-k8s permissions
  infrastructure/kubernetes/workflows-default/daskkubernetes-role.yaml
  infrastructure/kubernetes/workflows-default/kustomization.yaml
  infrastructure/kubernetes/workflows-default/workflows-default-dask-rolebinding.yaml
Labels: enhancement

#108 Remove cruft template from workflow
  workflows/dc6-workflow.yaml
Labels: enhancement

#112 Add "biascorrect-kind" workflow parameter for QDM training
  workflows/dc6-workflow.yaml
Labels: enhancement

#113 Bump argo-workflows to minor release v3.1.0
  infrastructure/kubernetes/argo/kustomization.yaml
Labels: bug, enhancement

#114 Tweaks to main workflow based on recent prototype run
  workflows/dc6-workflow.yaml
Labels: enhancement

#111 add zarr validation and write to azure
  notebooks/era5_workflow/validate_zarrs_and_write_to_azure.ipynb
Labels: enhancement
