Repository ClimateImpactLab/downscaleCMIP6, pull requests merged in 2022-01, with the labels that each got.

#501 Explicitly slice input data to train-qdm
  workflows/templates/qdm.yaml
Labels: bug

#504 Fix precip workflows killed before finishing
  workflows/templates/e2e-pr-jobs.yaml
Labels: bug

#509 Deploy new e2e-tasmin-jobs.yaml workflowtemplate
  workflows/templates/kustomization.yaml
Labels: bug, infrastructure

#511 extend minimum temperature tolerance from 150 K to 130 K
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: bug

#515 Fix precip downscaling not using max-capped bias-corrected data as input
  workflows/templates/biascorrectdownscale-precipitation.yaml
Labels: bug

#516 Fixes error in bad QPLAD coarse reference regrid method
  workflows/templates/qplad.yaml
Labels: bug

#517 Fix bad cyclic treatment in coarse reference regrid
  workflows/templates/qplad.yaml
Labels: bug

#519 Fix bad random draws in QDM wet-day correction
  workflows/templates/qdm-preprocess.yaml
Labels: bug

#520 Remove workflow cruft from biascorrectdownscale-pr template
  workflows/templates/biascorrectdownscale-precipitation.yaml
  workflows/templates/e2e-pr-jobs.yaml
Labels: enhancement

#521 Swap order of QDM biascorrection regridding and wet-day correction
  workflows/templates/qdm-preprocess.yaml
Labels: enhancement

#522 Split apply-WDF-mask for QPLAD into two parallel steps in new precip references creation workflow
  workflows/templates/create-pr-references.yaml
Labels: enhancement

#518 Add WorkflowTemplate to create reference precip datasets for input to qplad/qdm
  workflows/templates/create-pr-references.yaml
  workflows/templates/kustomization.yaml
Labels: enhancement
