Repository ClimateImpactLab/downscaleCMIP6, pull requests merged in 2022-02, with the labels that each got.

#527 Add 360 day calendar support to clean-cmip6
  workflows/templates/clean-cmip6.yaml
Labels: enhancement

#531 Dynamically detect non-time dims in regrid
  workflows/templates/distributed-regrid.yaml
Labels: bug, enhancement

#532 manually correct NorESM2 LM raw historical longitude bounds
  notebooks/downscaling_pipeline/correct-NorESM2-LM-raw-historical-lon-bounds.ipynb
Labels: bug

#579 Increase valid tasmin, tasmax range max to allow hot UKESM1-0, HadGEM3
  workflows/templates/qualitycontrol-check-cmip6.yaml
Labels: enhancement

#580 Update dodola in standardize-cmip6
  workflows/templates/clean-cmip6.yaml
Labels: bug

#584 add ssp585 to KACE-0-1-G-tasmax.yaml and add tasmin, pr parameter files.
  workflows/parameters/KACE-1-0-G-pr.yaml
  workflows/parameters/KACE-1-0-G-tasmax.yaml
  workflows/parameters/KACE-1-0-G-tasmin.yaml
Labels: enhancement

#585 add HadGEM-GC31-MM parameter files
  workflows/parameters/HadGEM3-GC31-MM-pr.yaml
  workflows/parameters/HadGEM3-GC31-MM-tasmax.yaml
  workflows/parameters/HadGEM3-GC31-MM-tasmin.yaml
Labels: parameter file
